export const titles: Record<string, string> = {
  agents: "Agents",
  skills: "Skills",
  tools: "工具",
  models: "模型连接",
  wiki: "知识库",
  members: "空间成员",
  editor: "Agent 开发",
  use: "发布应用",
};
export const descriptions: Record<string, string> = {
  agents: "配置、发布并运行团队的 Agent。",
  skills: "导入 SKILL.md 技能目录，复用指令、脚本与参考资料。",
  tools: "连接外部 MCP 服务，或由平台托管 Python 工具。",
  models: "管理聊天模型与知识库向量化模型。",
  wiki: "上传团队资料，通过检索为回答提供依据。",
  members: "空间成员共享本空间的 Agent 与资源。",
};
export const statusNames: Record<string, string> = {
  configured: "已配置",
  ready: "就绪",
  failed: "失败",
  empty: "未上传",
  building: "构建中",
  connecting: "连接中",
  environment_missing: "缺少 Docker",
  queued: "等待执行",
  running: "执行中",
  succeeded: "已完成",
  cancelled: "已取消",
  interrupted: "已中断",
  needs_input: "等待补充",
  pending: "待执行",
  in_progress: "执行中",
  completed: "已完成",
};
export const eventNames: Record<string, string> = {
  "run.resumed": "恢复任务",
  "run.blocked": "等待补充信息",
  "plan.updated": "调整执行计划",
  "completion.checking": "检查任务完成情况",
  "completion.checked": "完成检查结果",
  "context.compacted": "压缩任务上下文",
  "tool.uncertain": "检查中断调用结果",
  "run.created": "任务已创建",
  "run.started": "开始执行",
  "model.started": "模型调用",
  "plan.created": "生成执行计划",
  "step.started": "步骤开始",
  "step.completed": "步骤完成",
  "tool.started": "调用工具",
  "tool.completed": "工具完成",
  "tool.failed": "工具失败",
  "skill.loaded": "加载技能",
  "knowledge.retrieved": "检索知识库",
  "subagent.created": "创建子 Agent",
  "subagent.completed": "子 Agent 完成",
  "subagent.failed": "子 Agent 失败",
  "run.completed": "任务完成",
  "run.failed": "任务失败",
  "run.cancelled": "任务取消",
};
